my_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('all-stamps/',views.all_stamps_index, name='all-stamp-index'),

    path('stamps/', views.stamps_index, name='stamp-index'),
    path('stamps/<int:pk>/', views.StampDetail.as_view(), name='stamp-detail'),
    path('stamps/create/', views.StampCreate.as_view(), name='stamp-create'),
    path('stamps/<int:pk>/update/', views.StampUpdate.as_view(), name='stamp-update'),
    path('stamps/<int:pk>/delete/', views.StampDelete.as_view(), name='stamp-delete'),

    path('stamps/<int:stamp_id>/stop-create/', views.StopCreate.as_view(), name='stop-create'),
    path('stamps/<int:stamp_id>/stop/<int:pk>/stop-update', views.StopUpdate.as_view(), name='stop-update'),
    path('stamps/<int:stamp_id>/stop/<int:pk>/stop-delete', views.StopDelete.as_view(), name='stop-delete'),

    path('accounts/signup/', views.signup, name='signup'),

]

stamped/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')), # Mounts my_app's routes at the root URL
    path('accounts/', include('django.contrib.auth.urls')),
]

my_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

SEASON_CHOICES = [ 
    ('spring', 'Spring'), # each item is a (value, label) pair
    ('summer', 'Summer'), 
    ('fall', 'Fall'),
    ('winter', 'Winter'),
]

COUNTRY_CHOICES = [
    ('United States', '🇺🇸 United States'),
    ('Canada', '🇨🇦 Canada'),
    ('Mexico', '🇲🇽 Mexico'),
    ('Brazil', '🇧🇷 Brazil'),
    ('United Kingdom', '🇬🇧 United Kingdom'),
    ('Germany', '🇩🇪 Germany'),
    ('France', '🇫🇷 France'),
    ('Italy', '🇮🇹 Italy'),
    ('Spain', '🇪🇸 Spain'),
    ('Netherlands', '🇳🇱 Netherlands'),
    ('Switzerland', '🇨🇭 Switzerland'),
    ('Sweden', '🇸🇪 Sweden'),
    ('Australia', '🇦🇺 Australia'),
    ('Japan', '🇯🇵 Japan'),
    ('South Korea', '🇰🇷 South Korea'),
    ('China', '🇨🇳 China'),
    ('India', '🇮🇳 India'),
    ('South Africa', '🇿🇦 South Africa'),
    ('United Arab Emirates', '🇦🇪 United Arab Emirates'),
    ('Argentina', '🇦🇷 Argentina'),
]

RATING_CHOICES = [
    (5, '⭐️⭐️⭐️⭐️⭐️'),
    (4, '⭐️⭐️⭐️⭐️'),
    (3, '⭐️⭐️⭐️'),
    (2, '⭐️⭐️'),
    (1, '⭐️'),
]


class Stamp(models.Model):
    name = models.CharField(max_length=100, choices=COUNTRY_CHOICES, default=COUNTRY_CHOICES[0][0])
    days = models.IntegerField()
    season = models.CharField(max_length=100, choices=SEASON_CHOICES, default=SEASON_CHOICES[0][0])
    year = models.IntegerField()
    description = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE) # linking a Stamp to a User

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("stamp-detail", kwargs={"pk": self.pk}) # refer to "pk" (primary key) because I created detail page as a class-based view and that is what is passed
    
class Stop(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField('Visit Date')
    rating = models.IntegerField(choices=RATING_CHOICES, default=RATING_CHOICES[0][0])
    
    stamp = models.ForeignKey(Stamp, on_delete=models.CASCADE)
    # In a one-to-many relationship, the on_delete=models.CASCADE is required.
    # It ensures that if a Stamp record is deleted, all of the child Stops will be deleted automatically as well
        # - thus avoiding orphan records for Stops that are no longer tied to an existing Stamp.
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("stamp-detail", kwargs={"pk": self.stamp.pk}) # reference stamp because we are redirecting to the stamp details page

    class Meta:
        ordering = ['-date']

my_app/forms.py
from django import forms
from .models import Stop

class StopForm(forms.ModelForm):
    class Meta:
        model = Stop
        fields = ['name', 'date', 'rating']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

my_app/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Stamp, Stop
from.forms import StopForm

# Create your views here.

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('stamp-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

####

class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

def all_stamps_index(request):
    stamps = Stamp.objects.all()
    return render(request, 'stamps/all_index.html', {'stamps': stamps})

####

@login_required
def stamps_index(request):
    stamps = Stamp.objects.filter(user=request.user)
    return render(request, 'stamps/index.html', {'stamps': stamps})

class StampDetail(DetailView):
    model = Stamp
    template_name = 'stamps/detail.html'
    # context_object_name = 'stamp'
    extra_context = {'stop': Stop} # extra_context - how to pass through additional context using a class-based view as opposed to a view function (like 'stamps' above)

class StampCreate(LoginRequiredMixin, CreateView):
    model = Stamp
    fields = ['name', 'days', 'season', 'year', 'description']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class StampUpdate(LoginRequiredMixin, UpdateView):
    model = Stamp
    fields = ['days', 'season', 'year', 'description']
    def dispatch(self, request, *args, **kwargs):
        stamp = self.get_object()
        if stamp.user != self.request.user:
            return redirect('stamp-detail', pk=stamp.pk)

        return super().dispatch(request, *args, **kwargs)

class StampDelete(LoginRequiredMixin, DeleteView):
    model = Stamp
    success_url = '/stamps/'
    def dispatch(self, request, *args, **kwargs):
        stamp = self.get_object()
        if stamp.user != self.request.user:
            return redirect('stamp-detail', pk=stamp.pk)

        return super().dispatch(request, *args, **kwargs)

####

class StopCreate(LoginRequiredMixin, CreateView):
    model = Stop
    form_class = StopForm # fields are specified in StopForm in forms.py file
    def form_valid(self, form):
        form.instance.stamp_id = self.kwargs['stamp_id'] # attaches Stop form submission to parent Stamp
        return super().form_valid(form)

class StopUpdate(LoginRequiredMixin, UpdateView):
    model = Stop
    form_class = StopForm
    def dispatch(self, request, *args, **kwargs):
        stop = self.get_object()
        if stop.stamp.user != self.request.user:
            return redirect('stamp-detail', pk=stop.stamp.pk)

        return super().dispatch(request, *args, **kwargs)
   
    
class StopDelete(LoginRequiredMixin, DeleteView):
    model = Stop
    def get_success_url(self): # since directing to a dynamic URL (referencing stamp.pk) you have to use get_success_url instead of just success_url like in StampDelete
        return reverse("stamp-detail", kwargs={"pk": self.object.stamp.pk}) # have to include object.stamp because by default the current object is stop not stamp. So to access stamp you have to reference object
    def dispatch(self, request, *args, **kwargs):
        stop = self.get_object()
        if stop.stamp.user != self.request.user:
            return redirect('stamp-detail', pk=stop.stamp.pk)

        return super().dispatch(request, *args, **kwargs)

# Just testing data below - real data defined in model
'''
class Stamp:
    def __init__(self, name, days, season, year, description):
        self.name = name
        self.days = days
        self.season = season
        self.year = year
        self.description = description

stamps = [
    Stamp('Argentina', 12, 'Winter', '2023', 'Was so fun!'),
    Stamp('Japan', 8, 'Spring', '2022', 'Cherry blossoms everywhere, unforgettable!'),
    Stamp('Italy', 15, 'Summer', '2024', 'Ate pasta every single day, zero regrets.'),
    Stamp('Canada', 10, 'Fall', '2021', 'The maple leaves were unreal!'),
]
'''

my_app/templates/stamps/all_index.html
{% extends 'base.html' %} {% load static %}

{% block title %}
My Stamps
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/stamps/stamp-index.css' %}"/>
{% endblock %}

{% block content %}

<section class="page-header">
    <h1> All Stamps!</h1>
</section>

<section class="card-container">
  {% for stamp in stamps %}
  <div class="card">
    <a href="{% url 'stamp-detail' stamp.id %}">
      <h2 class="card-title">{{ stamp.get_name_display }}</h2>
      <p>{{ stamp.get_season_display }}, {{ stamp.year }}</p>
      <p>Stamped by: {{ stamp.user.username }}
    </a>
  </div>
  {% endfor %}
</section>


{% endblock %}

my_app/templates/stamps/detail.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
Details
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/stamps/stamp-detail.css' %}" />
{% endblock %} 

{% block content %}
<section class="stamp-container">
    <div class="stamp-actions">
        {% if stamp.user == request.user %}
        <a href="{% url 'stamp-index' %}" class="btn">Back to Your Stamps</a>
        {% else %}
        <a href="{% url 'all-stamp-index' %}" class="btn">Back to All Stamps</a>
        {% endif %}
    </div>
    <div class="stamp-details">
        <h2> {{ stamp.get_name_display }} 
        {% if stamp.days > 1 %}
        for {{ stamp.days }} days 
        {% else %}
        for {{ stamp.days }} day 
        {% endif %}
        </h2>
        <h1>{{ stamp.get_season_display }}, {{ stamp.year }} </h1>
        <h3>{{ stamp.description }}</h3>
        <div class="stamp-actions">
          {% if stamp.user == request.user %}
            <a href="{% url 'stamp-update' stamp.id %}" class="btn warn">Edit</a>
            <a href="{% url 'stamp-delete' stamp.id %}" class="btn danger">Delete</a>
          {% endif %}
        </div>
    </div>
</section>

<div class="stamp-details-container">
  <section class="stops">

    {% if stamp.user == request.user %}
    <a href="{% url 'stop-create' stamp.id %}" class="btn">Add a Stop</a>
    {% endif %}
    
    <div class="subsection-title">
      <h2>Past Stops</h2>
    </div>
    {% if stamp.stop_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>City</th>
          <th>Date</th>
          <th>Rating</th>
        </tr>
      </thead>
      <tbody>
        {% for stop in stamp.stop_set.all %}
          <tr>
            <td>{{stop.name}}</td>
            <td>{{stop.date}}</td>
            <td>{{stop.get_rating_display}}</td>
            {% if stamp.user == request.user %}
            <td><a href="{% url 'stop-update' stamp.id stop.id %}" class="btn warn">Edit</a></td>
            <td><a href="{% url 'stop-delete' stamp.id stop.id %}" class="btn danger">Delete</a></td>
            {% endif %}
            
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h3> No stops added yet! </h3>
    {% endif %}
  </section>
</div>
{% endblock %}

my_app/templates/stamps/index.html
{% extends 'base.html' %} {% load static %}

{% block title %}
My Stamps
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/stamps/stamp-index.css' %}"/>
{% endblock %}

{% block content %}

<section class="page-header">
    <h1> Your Stamps!</h1>
</section>

<section class="card-container">
  {% for stamp in stamps %}
  <div class="card">
    <a href="{% url 'stamp-detail' stamp.id %}">
      <h2 class="card-title">{{ stamp.get_name_display }}</h2>
      <p>{{ stamp.get_season_display }}, {{ stamp.year }}</p>
    </a>
  </div>
  {% endfor %}
</section>


    

{% endblock %}